### PR TITLE
Add Panasonic PTZ API Focus and Iris Control

### PR DESCRIPTION
**Pull request by tonsofpcs**
Add focus and iris control.

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature add - adds focus and iris control to Panasonic PTZ API

* **What is the current behavior?** (You can also link to an open issue here)
No current Focus/Iris control, only Zoom.

* **What is the new behavior (if this is a feature change)?**
Adds focus/iris control.

* **Other information**:
Reference: https://eww.pass.panasonic.co.jp/pro-av/support/content/guide/DEF/HE50_120_IP/HDIntegratedCamera_InterfaceSpecifications-E.pdf

### CODE REVIEW

**Review by sparkpunkd — APPROVED** [review]
On the surface, from a purely Typescipt perspective and without knowledge of the PTZ camera protocol, this looks fine. Approved on the assumption that the author has tested the features.

On merge, confirm that `continue-on-error` has been removed from the `.github/workflows/publish.yaml` file in line with commit 77ce56e796d59153bb06ad97c47e74440881296c

**Review by jstarpl — CHANGES_REQUESTED** [review]
@tonsofpcs Have you tested that this works? I see that you've added methods to `panasonicPTZAPI.ts`, but I don't see support for Focus and Iris in the `panasonicPTZ.ts` file, which should connect timeline objects to commands and then I think there should be some new type definitions for these timeline objects controlling Focus and Iris. Isn't that so?

**Comment by nytamin** [comment]
Hi @tonsofpcs!
Thanks for the PR, do you have any updates regarding the [previous comment in this thread](https://github.com/nrkno/tv-automation-state-timeline-resolver/pull/184#pullrequestreview-704035637)?

**Comment by nytamin** [comment]
Closing this due to no response from the PR author.
Feel free to reopen this later.

**Pull request closed without merging**
