### PR TITLE
Release 3 (WIP)

### PR DESCRIPTION
**Pull request by jstarpl**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
This PR introduces basic Panasonic PTZ camera support. Only cameras supporting the HTTP API interface are supported. So far, only preset recall and preset recall speed are supported.

### CODE REVIEW

**Comment by baltedewit** [comment]
I suppose the Lawo changes should be merged to master seperately, @nytamin?

**Comment by nytamin** [comment]
> I suppose the Lawo changes should be merged to master seperately, @nytamin?

You are referring to the /fix/lawo-success-false branch? If it's a hotfix, then yes.

**Comment by baltedewit** [comment]
No I mean c56144a0c854ba0959826029d88f9f965905e50a

I don't know yet if fix/lawo-success-false will be merged, Jesper wants that fix in the ember conn lib, I believe

**Comment by nytamin** [comment]
aha, got it.
no #c56144a is just a chore, no need to merge it separately.
In fact, I'll rename this PR to something more general, since I plan to merge the feature/TSPSendDevice into develop soon as well.

**Comment by baltedewit** [comment]
> I'll rename this PR to something more general

Just my two cents, but keeping PR's small and focussed would have my preference as that makes it easier to read back changes and possibly have discussions.

**Comment by nytamin** [comment]
Agreed, let's make future PRs from feature branches, targeting develop. All in the git-flow fashion 🙂

**Comment by olzzon** [comment]
2 keep the repo clean for the future, and to follow who has made what, it would make sense to make all feature branches in personal forks and then make PR’s to the develop branch in the master repository.
There’s already 15 branches here.

**Comment by baltedewit** [comment]
> There’s already 15 branches here.

Ah, yes, that's right. We need to start deleting feature branches after they have been merged to develop. I will try to make some time to clean up at least this repository.

**Comment by jesperstarkar** [comment]
@baltedewit I don't think this ember-change can go into production. It will completely fill our error logs at the moment.

**Pull request merged**
